#Статус сервера
status:
  mora: 'off'
  day: '1'
  month: '1'
#токен для подключения к боту дискорд
token: ''
#Увеличение стоимости идей за каждый закрытый шалкер(плоское)
ideaIncMod: 10
ideaCostBase: 25

#Базовая тактика для всех()
tacBase: 1
#Сколько тактики получает игрок за 1 исследование
tacGain: 0.1
#Базовая стоимость тактики
tacCostBase: 20
#Увеличение стоимости тактики за каждое исследование (1.0 + не увеличивается, 1.1 - +10% каждый раз)
tacIncMod: 1.0

#Бзовая цена на товары
tradeItems:

  BEEF: 2
  PORKCHOP: 2
  CHICKEN: 2
  MUTTON: 2
  COD: 2

  COOKED_BEEF: 4
  COOKED_PORKCHOP: 4
  COOKED_CHICKEN: 4
  COOKED_MUTTON: 4
  COOKED_COD: 4

  # Деревья и производные
  OAK_LOG: 2
  OAK_WOOD: 2
  OAK_PLANKS: 4
  DARK_OAK_LOG: 2
  DARK_OAK_WOOD: 2
  DARK_OAK_PLANKS: 4
  BIRCH_LOG: 2
  BIRCH_WOOD: 2
  BIRCH_PLANKS: 4
  SPRUCE_LOG: 2
  SPRUCE_WOOD: 2
  SPRUCE_PLANKS: 4
  JUNGLE_LOG: 2
  JUNGLE_WOOD: 2
  JUNGLE_PLANKS: 4
  CHERRY_LOG: 2
  CHERRY_WOOD: 2
  CHERRY_PLANKS: 4
  ACACIA_LOG: 2
  ACACIA_WOOD: 2
  ACACIA_PLANKS: 4
  MANGROVE_LOG: 2
  MANGROVE_WOOD: 2
  MANGROVE_PLANKS: 4
  PALE_OAK_LOG: 2
  PALE_OAK_WOOD: 2
  PALE_OAK_PLANKS: 4
  WOOD: 4

  # Металлы и ресурсы
  DIAMOND: 12
  AMETHYST_SHARD: 12
  GOLD_INGOT: 10
  IRON_INGOT: 5
  RAW_IRON: 3
  COPPER_INGOT: 4
  RAW_COPPER: 2
  COAL: 2

  # Блоки и камни
  SAND: 2
  COBBLESTONE: 2
  ANDESITE: 2
  DIORITE: 2
  GRANITE: 2
  COBBLED_DEEPSLATE: 2

  # Снаряжение и крафт
  IRON_SWORD:
    min: 3
    max: 6
  COPPER_SWORD:
    min: 2
    max: 5
  GUN:
    min: 4
    max: 7
  GUNPOWDER:
    min: 3
    max: 6
  CANNONBALL:
    min: 4
    max: 7
  BOOK: 12
  PAPER: 8
  LEATHER: 2
  FEATHER: 2
  WHITE_WOOL: 2

  # Еда и фермерство
  WHEAT: 1
  COOKED_MEAT: 3
  BREAD: 3
  MEAT: 2

  BEETROOT: 4
  POTATO: 4
  CARROT: 4

  SUGAR_CANE: 9
  COCOA_BEANS: 12
  MELON: 8
  PUMPKIN: 5

  # Прочее
  GLOWSTONE_DUST: 8 # Специи
  GREEN_DYE: 6      # Чай

townSize: 5 #Радиус и городов (в чанках) больше 15 не ставить
townDistanceMod: 2 #Модификатор минимального расстояния между городами(townDistance = townSize * townDistanceMod), МИНИМУМ - 2
#Прирост ОИ от зданий
universityIncome: 3
schoolIncome: 1
ministryOiIncome: 5

#set false, чтобы выключить сообщение при загрузке плагина
debug: true